wandb_version: 1

out_dir:
  desc: null
  value: perliment_out
eval_interval:
  desc: null
  value: 250
log_interval:
  desc: null
  value: 10
eval_iters:
  desc: null
  value: 200
eval_only:
  desc: null
  value: false
always_save_checkpoint:
  desc: null
  value: false
init_from:
  desc: null
  value: scratch
wandb_log:
  desc: null
  value: true
wandb_project:
  desc: null
  value: parliment-char
wandb_run_name:
  desc: null
  value: mini-gpt
dataset:
  desc: null
  value: parliment
gradient_accumulation_steps:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 64
block_size:
  desc: null
  value: 256
n_layer:
  desc: null
  value: 6
n_head:
  desc: null
  value: 6
n_embd:
  desc: null
  value: 384
dropout:
  desc: null
  value: 0.3
bias:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.001
max_iters:
  desc: null
  value: 7000
weight_decay:
  desc: null
  value: 1.0
beta1:
  desc: null
  value: 0.9
beta2:
  desc: null
  value: 0.99
grad_clip:
  desc: null
  value: 0.0
decay_lr:
  desc: null
  value: true
warmup_iters:
  desc: null
  value: 100
lr_decay_iters:
  desc: null
  value: 5000
min_lr:
  desc: null
  value: 0.0001
backend:
  desc: null
  value: nccl
device:
  desc: null
  value: cuda
dtype:
  desc: null
  value: bfloat16
compile:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.8.13
    cli_version: 0.15.11
    framework: huggingface
    huggingface_version: 4.33.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696058896.362566
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.13
      5: 0.15.11
      6: 4.33.3
      8:
      - 5
      13: linux-x86_64
